# Site settings
author: Alexis Priore
title: Why did I decide to learn software development?
header-img: img/home-bg.png
email: alexispriore@gmail.com
copyright_name: Alexis Priore
description: > # this means to ignore newlines until "baseurl:"
  From Restaurants to Coding 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Alexis122

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
